### ISSUE TITLE
Error Dialog on ping if WiFi is off

### ISSUE THREAD

**Issue by andreafalzetti** [kingsloi/iskingsley.online#1]
As I told you on Reddit, this is a nice and cool idea. I have forked your project in isandrea.online :)

I'm having an issue when the WIFI is switched off, I get the error dialog as follows:

I briefly look at your code in `index.js` and I can see the Exception handler. I think maybe you can review it a little bit so it doesn't trigger a fatal error message while it should just "not pinging" the server.

![screen shot 2016-04-13 at 22 45 25](https://cloud.githubusercontent.com/assets/2318450/14510494/b5abe1f0-01c9-11e6-8bdc-c473ab87cd3c.jpg)

Also, where is the check log?

**Comment by kingsloi** [comment]
hey @andreafalzetti, cheers for actually submitting an issue!

Great point! I actually had no internet earlier, and that's where I found the app crashed if it couldn't ping, so I added an exception handler to not crash the app but didn't think about handling it a little better. I'm on it!

**Comment by andreafalzetti** [comment]
I'm updating to v2, I'll let you know my feedback!

**Comment by kingsloi** [comment]
Hey @andreafalzetti,

Check out that latest release. It alerts saying it cannot connect, and stops future pings (and unchecks enabled). 

Not sure if it's a nw.js problem or a node issue, but as soon as I package the app, I can't open the log file. It works when I build locally, but when I package it it doesn't open. I think it's possibly a permissions related. However, I alert with the path to the debug.log file. 

A link to the debug.log file is hidden by default, if you open settings and scroll a lil, you'll see a link to debug. 

Cheers buddy!
